Repository alamenai/rehook, pull requests merged in 2024-06, with the labels that each got.

#43 update: refactor useFetch hook
  src/hooks/__tests__/use-fetch.spec.ts
  src/hooks/__tests__/useFetch.spec.ts
  src/hooks/use-fetch.ts
  src/hooks/useFetch.ts
Labels: enhancement, feature

#44 fix: useHistory has duplicated files
  src/hooks/__tests__/useHistory.spec.ts
  src/hooks/useHistory.ts
Labels: bug

#45 feat: update useFetch to reject earlier calls if a later one is made
  package.json
  src/hooks/__tests__/use-fetch.spec.ts
  src/hooks/use-fetch.ts
Labels: enhancement, good first pull request

#42 feat: implement useTimeout hook for managing timeout
  src/hooks/__tests__/use-timeout.spec.ts
  src/hooks/use-timeout.ts
Labels: feature

#51 refactor: change configuration file
  .github/workflows/lint-and-test.yml
  README.md
  package.json
  rehook.config.ts
  src/App.tsx
  src/actions/env.ts
  src/hooks/use-env.ts
Labels: enhancement

#54 test: add unit test for useMediaQuery
  src/hooks/__tests__/use-media-query.spec.ts
Labels: testing

#55 feat: implement useSession for managing web sessions
  src/hooks/__tests__/use-session.spec.ts
  src/hooks/use-session.ts
Labels: feature
